<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INWS03011-02" ignored="0" name="Test" tests="13" failures="9" timestamp="2020-04-19T00:38:40 IST" time="15.331" errors="0">
  <testcase name="checkResponse" time="0.01" classname="com.employee.testcases.TC_003_POST_Employee_Record">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.employee.testcases.TC_003_POST_Employee_Record.checkResponse(TC_003_POST_Employee_Record.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkResponse -->
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testcases.TC_003_POST_Employee_Record">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.employee.testcases.TC_003_POST_Employee_Record.checkResponseTime(TC_003_POST_Employee_Record.java:72)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkStatusCode" time="0.002" classname="com.employee.testcases.TC_003_POST_Employee_Record">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.employee.testcases.TC_003_POST_Employee_Record.checkStatusCode(TC_003_POST_Employee_Record.java:64)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkStatusLine" time="0.001" classname="com.employee.testcases.TC_003_POST_Employee_Record">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.employee.testcases.TC_003_POST_Employee_Record.checkStatusLine(TC_003_POST_Employee_Record.java:82)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase name="checkContentLenght" time="0.003" classname="com.employee.testcases.TC_001_GET_ALL_Employee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employee.testcases.TC_001_GET_ALL_Employee.checkContentLenght(TC_001_GET_ALL_Employee.java:86)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkContentLenght -->
  <testcase name="checkResponse" time="0.012" classname="com.employee.testcases.TC_001_GET_ALL_Employee"/>
  <testcase name="checkResponseTime" time="0.002" classname="com.employee.testcases.TC_001_GET_ALL_Employee"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testcases.TC_001_GET_ALL_Employee">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.employee.testcases.TC_001_GET_ALL_Employee.checkStatusCode(TC_001_GET_ALL_Employee.java:66)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkContentType" time="0.001" classname="com.employee.testcases.TC_002_GET_Single_Record"/>
  <testcase name="checkResponse" time="0.001" classname="com.employee.testcases.TC_002_GET_Single_Record">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.employee.testcases.TC_002_GET_Single_Record.checkResponse(TC_002_GET_Single_Record.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkResponse -->
  <testcase name="checkResponseTime" time="0.0" classname="com.employee.testcases.TC_002_GET_Single_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testcases.TC_002_GET_Single_Record">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.employee.testcases.TC_002_GET_Single_Record.checkStatusCode(TC_002_GET_Single_Record.java:61)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkStatusLine" time="0.001" classname="com.employee.testcases.TC_002_GET_Single_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 400 Bad Request] but found [HTTP/1.1 200 OK]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 400 Bad Request] but found [HTTP/1.1 200 OK]
at com.employee.testcases.TC_002_GET_Single_Record.checkStatusLine(TC_002_GET_Single_Record.java:79)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
</testsuite> <!-- Test -->
